name: Build and Deploy

on:
  push:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: '.'
        submodules: true
    - uses: actions/checkout@v2
      with:
        repository: sh4869/dgen
        path: dgen
    - name: Install Rust tool chain latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build dgen
      run: cargo install --path .
      working-directory: ./dgen
    - name: Run dgen
      run: dgen
    - name: Build Diary Calendar
      run: cd dgen-calendar && yarn && yarn build && cd - && cp -r dgen-calendar/dist docs/calendar
    - name: Deploy files to Firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
          args: deploy --token $FIREBASE_TOKEN --only hosting --project diary-sh4869-sh
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "[DIARY] DEPLOY COMPLETE",
             "attachments": [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_HOOKS }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
