name: "update submodule"

on: 
  repository_dispatch:
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: update submodules
      run: |
        git submodule update --remote ./dgen-calendar
    - name: git commit
      run: |
        git config --local user.name "sh4869"
        git config --local user.email "nobuk4869@gmail.com"
        git add -A
        git status
        git commit -m "update submodule by actions"
    - name: Git push
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
