name: "update submodule"

on: 
  repository_dispatch:
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        ref: diary-data
    - name: update submodules
      run: |
        git submodule update --remote ./dgen-calendar
    - name: git commit
      run: |
        git config --local user.name "sh4869"
        git config --local user.email "nobuk4869@gmail.com"
        git add -A
        git status
        git commit -m "update submodule by actions"
        git push
